package org.investpro.trading.tradability;

public enum TradabilityStatus {
    FULLY_TRADABLE,
    VIEW_ONLY,
    MARKET_CLOSED,
    DISABLED,
    HALTED,
    CANCEL_ONLY,
    LIMIT_ONLY,
    POST_ONLY,
    AUCTION_ONLY,
    REDUCE_ONLY,
    CLOSE_ONLY,
    PERMISSION_DENIED,
    REGION_RESTRICTED,
    ACCOUNT_TYPE_RESTRICTED,
    MARGIN_RESTRICTED,
    API_KEY_RESTRICTED,
    UNSUPPORTED_ORDER_TYPE,
    UNSUPPORTED_PRODUCT_TYPE,
    MIN_SIZE_INVALID,
    MAX_SIZE_INVALID,
    LIQUIDITY_UNAVAILABLE,
    INACTIVE,
    UNKNOWN

}
