package org.investpro;

public enum TRADE_EVENTS {
    TRADE_STARTED,
    TRADE_COMPLETED,
    TRADE_CANCELLED,
    TRADE_FAILED,
    TRADE_REVERSED,

    OPENING_STOP_BUY_ORDER,
    OPENING_STOP_SELL_ORDER,
    OPENING_LIMIT_SELL_ORDER,
    OPENING_LIMIT_BUY_ORDER,
    OPENING_STOP_ORDER,
    OPENING_LIMIT_ORDER,
    OPENING_MARKET_BUY_ORDER,
    OPENING_MARKET_SELL_ORDER,
    OPENING_MARKET_LIMIT_SELL_ORDER


}
