package org.investpro.terminal.domain;

public enum BrokerActivityEventType {
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_PARTIALLY_FILLED,
    ORDER_FILLED,
    ORDER_CANCELED,
    ORDER_EXPIRED,
    ORDER_REPLACED,
    POSITION_OPENED,
    POSITION_UPDATED,
    POSITION_CLOSED,
    BALANCE_UPDATED,
    FEE_CHARGED,
    TRANSFER_DEPOSIT,
    TRANSFER_WITHDRAWAL,
    MARGIN_WARNING,
    LIQUIDATION_WARNING,
    RECONCILIATION_STARTED,
    RECONCILIATION_DIFFERENCE_FOUND,
    RECONCILIATION_RESOLVED
}
