package org.investpro.exchange.resilience;

import lombok.extern.slf4j.Slf4j;
import org.investpro.exchange.resilience.model.EndpointType;
import org.jetbrains.annotations.NotNull;

import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Adaptive REST polling engine that dynamically adjusts polling intervals
 * based on trading activity, position state, and market conditions.
 *
 * <p>Reduces unnecessary HTTP traffic during idle periods:
 * <ul>
 *   <li>Active trading: critical endpoints refreshed every ~1s via WebSocket;
 *       REST fallback at 1–3s.</li>
 *   <li>Normal: REST polling at 5–15s.</li>
 *   <li>Idle (no positions, no orders, no strategy activity): 30–60s.</li>
 *   <li>Smart idle mode: maximum reduction, minimal network footprint.</li>
 * </ul>
 *
 * <p>This class does not own any scheduler threads — it is a pure
 * policy engine that tells the caller what interval to use.
 * {@link org.investpro.exchange.infrastructure.PollingExchangeStreamer}
 * consults it for current intervals.
 */
@Slf4j
public final class AdaptivePollingEngine {

    // ─ Interval constants (seconds) ────────────────────────────────────────────

    private static final long ACTIVE_POLL_SECONDS = 1;
    private static final long NORMAL_POLL_SECONDS = 10;
    private static final long IDLE_POLL_SECONDS = 30;
    private static final long SMART_IDLE_POLL_SECONDS = 60;

    // Non-critical endpoints are always polled slower
    private static final long NON_CRITICAL_ACTIVE_SECONDS = 10;
    private static final long NON_CRITICAL_NORMAL_SECONDS = 30;
    private static final long NON_CRITICAL_IDLE_SECONDS = 120;
    private static final long NON_CRITICAL_SMART_IDLE_SECONDS = 300;

    // ─ Activity tracking ──────────────────────────────────────────────────

    private final AtomicInteger openPositions = new AtomicInteger(0);
    private final AtomicInteger pendingOrders = new AtomicInteger(0);
    private final AtomicBoolean activeExecution = new AtomicBoolean(false);
    private final AtomicBoolean strategyLabActive = new AtomicBoolean(false);
    private final AtomicReference<Instant> lastSignalAt = new AtomicReference<>(null);
    private final AtomicReference<Instant> lastTradeAt = new AtomicReference<>(null);
    private final AtomicLong signalCount = new AtomicLong(0);
    private final AtomicBoolean smartIdleMode = new AtomicBoolean(false);

    // Per-endpoint override (e.g., manual throttle during circuit recovery)
    private final Map<EndpointType, Long> endpointOverrides = new ConcurrentHashMap<>();

    private final String exchangeName;

    public AdaptivePollingEngine(@NotNull String exchangeName) {
        this.exchangeName = exchangeName;
    }

    // ─ Activity signals ───────────────────────────────────────────────────

    /** Call when the open position count changes. */
    public void onPositionCountChanged(int openPositionCount) {
        openPositions.set(Math.max(0, openPositionCount));
        reevaluateIdleMode();
    }

    /** Call when the pending order count changes. */
    public void onPendingOrderCountChanged(int pendingOrderCount) {
        pendingOrders.set(Math.max(0, pendingOrderCount));
        reevaluateIdleMode();
    }

    /** Call when execution is in flight. */
    public void onExecutionStarted() {
        activeExecution.set(true);
        smartIdleMode.set(false);
    }

    /** Call when execution completes or is cancelled. */
    public void onExecutionCompleted() {
        activeExecution.set(false);
        lastTradeAt.set(Instant.now());
        reevaluateIdleMode();
    }

    /** Call when a signal is generated by the strategy engine. */
    public void onSignalGenerated() {
        lastSignalAt.set(Instant.now());
        signalCount.incrementAndGet();
        strategyLabActive.set(true);
        smartIdleMode.set(false);
    }

    /** Call when the Strategy Lab is started or stopped. */
    public void onStrategyLabActiveChanged(boolean active) {
        strategyLabActive.set(active);
        reevaluateIdleMode();
    }

    /**
     * Returns the recommended polling interval in seconds for the given endpoint.
     *
     * @param endpoint the endpoint being polled
     * @return recommended interval in seconds
     */
    public long recommendedIntervalSeconds(@NotNull EndpointType endpoint) {
        // Per-endpoint override takes highest precedence
        Long override = endpointOverrides.get(endpoint);
        if (override != null) return override;

        ActivityLevel level = currentActivityLevel();

        if (endpoint.critical) {
            return switch (level) {
                case ACTIVE -> ACTIVE_POLL_SECONDS;
                case NORMAL -> NORMAL_POLL_SECONDS;
                case IDLE -> IDLE_POLL_SECONDS;
                case SMART_IDLE -> SMART_IDLE_POLL_SECONDS;
            };
        } else {
            return switch (level) {
                case ACTIVE -> NON_CRITICAL_ACTIVE_SECONDS;
                case NORMAL -> NON_CRITICAL_NORMAL_SECONDS;
                case IDLE -> NON_CRITICAL_IDLE_SECONDS;
                case SMART_IDLE -> NON_CRITICAL_SMART_IDLE_SECONDS;
            };
        }
    }

    /**
     * Returns the current activity level of the trading runtime.
     *
     * @return current activity level
     */
    public @NotNull ActivityLevel currentActivityLevel() {
        if (activeExecution.get()) return ActivityLevel.ACTIVE;
        if (openPositions.get() > 0 || pendingOrders.get() > 0) return ActivityLevel.NORMAL;
        if (smartIdleMode.get()) return ActivityLevel.SMART_IDLE;
        if (recentSignalActivity()) return ActivityLevel.NORMAL;
        return ActivityLevel.IDLE;
    }

    /** Returns true if smart idle mode is active. */
    public boolean isSmartIdleMode() {
        return smartIdleMode.get();
    }

    /**
     * Sets a per-endpoint polling override (used during circuit recovery or pressure).
     *
     * @param endpoint endpoint to override
     * @param intervalSeconds override interval in seconds
     */
    public void setEndpointOverride(@NotNull EndpointType endpoint, long intervalSeconds) {
        endpointOverrides.put(endpoint, intervalSeconds);
        log.debug("Polling override set: {}/{} → {}s", exchangeName, endpoint, intervalSeconds);
    }

    /** Clears any per-endpoint polling override. */
    public void clearEndpointOverride(@NotNull EndpointType endpoint) {
        endpointOverrides.remove(endpoint);
    }

    /** Returns diagnostic information about the current polling state. */
    public @NotNull String diagnostics() {
        return "AdaptivePolling[%s] level=%s idle=%s positions=%d orders=%d execution=%s strategy=%s"
                .formatted(
                        exchangeName,
                        currentActivityLevel(),
                        smartIdleMode.get(),
                        openPositions.get(),
                        pendingOrders.get(),
                        activeExecution.get(),
                        strategyLabActive.get()
                );
    }

    // ─────────────────────────────────────────────────────────────────────────────────

    private boolean recentSignalActivity() {
        Instant lastSignal = lastSignalAt.get();
        if (lastSignal == null) return false;
        return Duration.between(lastSignal, Instant.now()).toMinutes() < 5;
    }

    private void reevaluateIdleMode() {
        boolean shouldBeSmartIdle = openPositions.get() == 0
                && pendingOrders.get() == 0
                && !activeExecution.get()
                && !strategyLabActive.get()
                && !recentSignalActivity();
        smartIdleMode.set(shouldBeSmartIdle);
        if (shouldBeSmartIdle) {
            log.debug("Smart idle mode activated for {} — reducing polling", exchangeName);
        }
    }

    /** Trading activity levels used to select polling intervals. */
    public enum ActivityLevel {
        /** Execution in flight, every millisecond matters. */
        ACTIVE,
        /** Positions or orders open; standard monitoring needed. */
        NORMAL,
        /** No active positions or orders; relaxed polling. */
        IDLE,
        /** Fully quiescent; minimal polling, maximum conservation. */
        SMART_IDLE
    }
}
