package org.investpro.strategy.lifecycle;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * AI recommendation report for replacing a degraded strategy assignment.
 * Generated by {@link org.investpro.strategy.ai.AIReplacementEngine}.
 * This is advisory only - the StrategyAssignmentManager applies any replacement.
 */
@Getter
@Builder
@ToString
public class AIReplacementReport {

    /** Unique report identifier (UUID). */
    @Builder.Default
    private final String reportId = UUID.randomUUID().toString();

    /** Assignment identifier being evaluated. */
    private final String assignmentId;

    /** Current strategy identifier. */
    private final String currentStrategyId;

    /** Trading symbol. */
    private final String symbol;

    /** Timeframe. */
    private final String timeframe;

    /** AI recommendation (KEEP / REPLACE / DEMOTE / PAUSE). */
    private final AIReplacementRecommendation recommendation;

    /** AI confidence in this recommendation (0.0-1.0). */
    private final double aiConfidence;

    /** Human-readable reasoning summary. */
    private final String reasoningSummary;

    /** Suggested replacement strategy identifier (null if no replacement recommended). */
    private final String candidateStrategyId;

    /** Composite score of the candidate replacement strategy. */
    private final double candidateScore;

    /** Composite score of the current strategy. */
    private final double currentScore;

    /** Detailed reasons driving the replacement recommendation. */
    private final List<String> replacementReasons;

    /** Expected improvement in regime fit if replacement is applied. */
    private final double regimeFitImprovement;

    /** Expected improvement in risk profile if replacement is applied. */
    private final double riskProfileImprovement;

    /** Human-readable comparison of recent performance between strategies. */
    private final String recentPerformanceComparison;

    /** Timestamp when this report was generated. */
    private final Instant generatedAt;
}
