package org.investpro.strategy.lifecycle;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Report validating whether a strategy in paper trading is ready to go live.
 * Generated by {@link org.investpro.strategy.ai.AIStrategyValidationEngine}.
 */
@Getter
@Builder
@ToString
public class StrategyValidationReport {

    /** Unique report identifier (UUID). */
    @Builder.Default
    private final String reportId = UUID.randomUUID().toString();

    /** Assignment identifier. */
    private final String assignmentId;

    /** Strategy identifier. */
    private final String strategyId;

    /** Trading symbol. */
    private final String symbol;

    /** Timeframe. */
    private final String timeframe;

    /** Number of days the paper trading period covered. */
    private final int paperTradePeriodDays;

    /** Total number of paper trades executed. */
    private final int totalPaperTrades;

    /** Win rate during paper trading (fraction). */
    private final double paperWinRate;

    /** Profit factor during paper trading. */
    private final double paperProfitFactor;

    /** Maximum drawdown during paper trading (fraction). */
    private final double paperDrawdown;

    /** Average expected return per trade during paper trading. */
    private final double paperExpectancy;

    /** Score for signal quality (0.0-1.0). */
    private final double signalQualityScore;

    /** Score for execution quality (0.0-1.0). */
    private final double executionQualityScore;

    /** Score for risk management behaviour (0.0-1.0). */
    private final double riskBehaviorScore;

    /** Score for consistency of performance (0.0-1.0). */
    private final double consistencyScore;

    /** AI decision (APPROVE / REJECT / NEEDS_MORE_DATA / PAPER_TRADE_FIRST). */
    private final AIReviewDecision aiDecision;

    /** AI confidence in this validation decision (0.0-1.0). */
    private final double aiConfidence;

    /** Human-readable AI reasoning summary. */
    private final String aiReasoningSummary;

    /** True if paper trading results align with backtest expectations. */
    private final boolean behavingAsExpected;

    /** True if performance has been degrading over the paper trading period. */
    private final boolean performanceDegrading;

    /** True if a market regime change is suspected to be affecting performance. */
    private final boolean regimeChanging;

    /** True if signal confidence values remain valid predictors of outcomes. */
    private final boolean confidenceStillValid;

    /** True if the AI approves this strategy for live trading. */
    private final boolean approvedForLive;

    /** Specific reasons for rejection (empty if approved). */
    private final List<String> rejectionReasons;

    /** Timestamp when this report was generated. */
    private final Instant validatedAt;
}
