package org.investpro.strategy.lifecycle;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;
import java.util.List;

/**
 * Records what a strategy has learned from its live and paper trading history.
 * Updated by {@link org.investpro.strategy.performance.StrategyLearningEngine}
 * after each trade observation.
 */
@Getter
@Builder
@ToString
public class StrategyLearningProfile {

    /** Assignment identifier. */
    private final String assignmentId;

    /** Strategy identifier. */
    private final String strategyId;

    /** Trading symbol. */
    private final String symbol;

    /** Timeframe. */
    private final String timeframe;

    /** Market regime names where this strategy performs best. */
    private final List<String> bestRegimes;

    /** Market regime names where this strategy performs worst. */
    private final List<String> worstRegimes;

    /** Trading sessions (e.g. LONDON, NEW_YORK) where performance is best. */
    private final List<String> bestSessions;

    /** Trading sessions where performance is worst. */
    private final List<String> worstSessions;

    /**
     * Optimal signal confidence threshold, learned from win/loss patterns.
     * Signals below this threshold are more likely to lose.
     */
    private final double optimalConfidenceThreshold;

    /** Average confidence of winning trades. */
    private final double avgWinConfidence;

    /** Average confidence of losing trades. */
    private final double avgLossConfidence;

    /** Conditions associated with profitable trades. */
    private final List<String> profitableConditions;

    /** Conditions associated with unprofitable trades. */
    private final List<String> unprofitableConditions;

    /** Market or system conditions that historically triggered drawdowns. */
    private final List<String> drawdownTriggers;

    /** Incremented each time the profile is updated with new observations. */
    private final int learningVersion;

    /** Total number of trades this profile has been trained on. */
    private final int learningObservations;

    /** Timestamp of the most recent learning update. */
    private final Instant lastLearnedAt;

    /** Human-readable notes generated by the learning engine. */
    private final String adaptationNotes;
}
