package org.investpro.strategy.lifecycle;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Health assessment report for an active strategy assignment.
 * Generated by {@link org.investpro.strategy.ai.AIStrategyHealthEngine}.
 */
@Getter
@Builder
@ToString
public class StrategyHealthReport {

    /** Unique report identifier (UUID). */
    @Builder.Default
    private final String reportId = UUID.randomUUID().toString();

    /** Assignment identifier. */
    private final String assignmentId;

    /** Strategy identifier. */
    private final String strategyId;

    /** Trading symbol. */
    private final String symbol;

    /** Timeframe. */
    private final String timeframe;

    /** Current health level classification. */
    private final StrategyHealthLevel healthLevel;

    /** Previous health level (null if first report). */
    private final StrategyHealthLevel previousHealthLevel;

    /** Win rate across all trades. */
    private final double winRate;

    /** Profit factor across all trades. */
    private final double profitFactor;

    /** Maximum drawdown experienced. */
    private final double maxDrawdown;

    /** Average expected return per trade. */
    private final double expectancy;

    /** Sharpe ratio. */
    private final double sharpeRatio;

    /** Sortino ratio. */
    private final double sortinoRatio;

    /** Win rate for the most recent 20 trades. */
    private final double recentWinRate;

    /** Profit factor for the most recent 20 trades. */
    private final double recentProfitFactor;

    /** Composite health score (0-100). */
    private final double healthScore;

    /** AI-generated explanation of the health status and any changes. */
    private final String aiExplanation;

    /** List of alert messages triggered during assessment. */
    private final List<String> triggeredAlerts;

    /** AI recommendation for what to do with this strategy. */
    private final AIReplacementRecommendation recommendedAction;

    /** True if a market regime shift may be contributing to performance changes. */
    private final boolean isRegimeShifting;

    /** Timestamp when this report was generated. */
    private final Instant generatedAt;

    /**
     * @return true if health has declined since the previous report.
     *         Returns false if there is no previous report to compare against.
     */
    public boolean isDegrading() {
        return previousHealthLevel != null
                && healthLevel.priority < previousHealthLevel.priority;
    }
}
