package org.investpro.signal;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.investpro.models.trading.TradePair;
import org.investpro.utils.Side;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Trading signal generated by an agent or strategy.
 * 
 * Note: Prefer StrategySignal which provides complete signal context including
 * entry/exit prices, risk/reward ratios, and confidence metrics.
 */
@Data
@Slf4j
public class Signal {

    private final String signalId;
    private final TradePair tradePair;
    private final Side side;
    private final double confidence;
    private final String strategyName;
    private final List<String> reasons;
    private final Instant timestamp;

    public Signal(TradePair tradePair, Side side, double confidence, String strategyName, List<String> reasons) {
        this.signalId = UUID.randomUUID().toString();
        this.tradePair = tradePair;
        this.side = side;
        this.confidence = Math.max(0.0, Math.min(1.0, confidence));
        this.strategyName = strategyName == null || strategyName.isBlank() ? "unknown" : strategyName;
        this.reasons = List.copyOf(reasons == null ? List.of() : reasons);
        this.timestamp = Instant.now();
    }

    @Override
    public String toString() {
        return "Signal{strategy signal='%s', confidence=%s, strategyName='%s', tradePair=%s}".formatted(side,
                confidence, strategyName, tradePair);
    }
}
