package org.investpro.core.agents.signal;

import lombok.Getter;
import org.investpro.models.trading.TradePair;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Trading signal generated by an agent or strategy.
 */
@Getter
public class Signal {

    private final String signalId;
    private final TradePair tradePair;
    private final String side;
    private final double confidence;
    private final String strategyName;
    private final List<String> reasons;
    private final Instant timestamp;

    public Signal(TradePair tradePair, String side, double confidence, String strategyName, List<String> reasons) {
        this.signalId = UUID.randomUUID().toString();
        this.tradePair = tradePair;
        this.side = side == null ? "HOLD" : side.toUpperCase();
        this.confidence = Math.max(0.0, Math.min(1.0, confidence));
        this.strategyName = strategyName == null || strategyName.isBlank() ? "unknown" : strategyName;
        this.reasons = List.copyOf(reasons == null ? List.of() : reasons);
        this.timestamp = Instant.now();
    }

    @Override
    public String toString() {
        return "Signal{side='%s', confidence=%s, strategyName='%s', tradePair=%s}".formatted(side, confidence, strategyName, tradePair);
    }
}
