from __future__ import annotations

import json
import logging
import time

from . import __version__
from .model import HeuristicMarketPredictor

LOGGER = logging.getLogger("investpro.predictor")


async def handle_message(websocket, predictor: HeuristicMarketPredictor, raw_message: str) -> None:
    data = json.loads(raw_message)
    request_type = data.get("type")
    request_id = data.get("requestId")

    if request_type == "health_check":
        await websocket.send(json.dumps({
            "type": "health_check_response",
            "requestId": request_id,
            "status": "ok",
            "version": __version__,
            "modelName": predictor.name,
            "timestamp": int(time.time())
        }))
        return

    if request_type == "batch_predict":
        predictions = []
        for candle in data.get("requests", []):
            p = predictor.predict(candle)
            predictions.append({
                "symbol": candle.get("symbol", ""),
                "prediction": p.label,
                "confidence": p.confidence,
                "probabilityUp": p.probability_up,
                "probabilityDown": p.probability_down,
                "model": predictor.name,
                "reason": f"Generated by {predictor.name}"
            })

        await websocket.send(json.dumps({
            "type": "batch_predict_response",
            "requestId": request_id,
            "predictions": predictions
        }))
        return

    await websocket.send(json.dumps({
        "type": "error",
        "requestId": request_id,
        "status": "error",
        "details": f"Unsupported request type: {request_type}"
    }))