from __future__ import annotations

import argparse
import asyncio
import json
import logging
import signal
import time
from typing import Any

import websockets
from websockets.server import WebSocketServerProtocol

from . import __version__
from .model import HeuristicMarketPredictor

LOGGER = logging.getLogger("investpro.predictor")


class PredictorWebSocketService:
    def __init__(self, predictor: HeuristicMarketPredictor) -> None:
        self.predictor = predictor
        self.feedback: list[tuple[str, str, float]] = []

    async def handle_message(self, websocket: WebSocketServerProtocol, raw_message: str) -> None:
        try:
            data = json.loads(raw_message)
        except json.JSONDecodeError:
            await websocket.send(json.dumps({
                "type": "error",
                "status": "error",
                "details": "Invalid JSON payload"
            }))
            return

        request_type = data.get("type")
        request_id = data.get("requestId")

        try:
            if request_type == "health_check":
                await websocket.send(json.dumps({
                    "type": "health_check_response",
                    "requestId": request_id,
                    "status": "ok",
                    "version": __version__,
                    "modelName": self.predictor.name,
                    "timestamp": int(time.time())
                }))

            elif request_type == "model_info":
                await websocket.send(json.dumps({
                    "type": "model_info_response",
                    "requestId": request_id,
                    "name": self.predictor.name,
                    "version": self.predictor.version,
                    "framework": self.predictor.framework,
                    "lastTrained": self.predictor.loaded_at
                }))

            elif request_type == "reload_model":
                model_path = data.get("modelPath")
                try:
                    details = self.predictor.reload(model_path)
                    status = "ok"
                except Exception as exc:
                    LOGGER.exception("Model reload failed")
                    status = "error"
                    details = str(exc)

                await websocket.send(json.dumps({
                    "type": "reload_model_response",
                    "requestId": request_id,
                    "status": status,
                    "details": details
                }))

            elif request_type == "trade_feedback":
                trade_id = data.get("tradeId", "")
                result = data.get("result", "")
                pnl = float(data.get("pnl", 0.0))
                self.feedback.append((trade_id, result, pnl))
                LOGGER.info(
                    "Received trade feedback: trade_id=%s result=%s pnl=%s",
                    trade_id,
                    result,
                    pnl,
                )

                await websocket.send(json.dumps({
                    "type": "trade_feedback_response",
                    "requestId": request_id,
                    "status": "ok"
                }))

            elif request_type == "batch_predict":
                requests = data.get("requests", [])
                predictions: list[dict[str, Any]] = []

                for candle in requests:
                    prediction = self.predictor.predict(candle)
                    predictions.append({
                        "symbol": candle.get("symbol", ""),
                        "prediction": prediction.label,
                        "confidence": prediction.confidence,
                        "probabilityUp": prediction.probability_up,
                        "probabilityDown": prediction.probability_down,
                        "model": self.predictor.name,
                        "reason": f"Generated by {self.predictor.name}"
                    })

                await websocket.send(json.dumps({
                    "type": "batch_predict_response",
                    "requestId": request_id,
                    "predictions": predictions
                }))

            elif request_type == "predict":
                candle = data.get("request", {})
                prediction = self.predictor.predict(candle)

                await websocket.send(json.dumps({
                    "type": "predict_response",
                    "requestId": request_id,
                    "prediction": prediction.label,
                    "confidence": prediction.confidence,
                    "probabilityUp": prediction.probability_up,
                    "probabilityDown": prediction.probability_down,
                    "model": self.predictor.name,
                    "reason": f"Generated by {self.predictor.name}"
                }))

            else:
                await websocket.send(json.dumps({
                    "type": "error",
                    "requestId": request_id,
                    "status": "error",
                    "details": f"Unsupported request type: {request_type}"
                }))

        except Exception as exc:
            LOGGER.exception("Failed handling WebSocket request")
            await websocket.send(json.dumps({
                "type": "error",
                "requestId": request_id,
                "status": "error",
                "details": str(exc)
            }))


async def websocket_handler(websocket: WebSocketServerProtocol, predictor_service: PredictorWebSocketService) -> None:
    LOGGER.info("Client connected from %s", getattr(websocket, "remote_address", None))
    try:
        async for message in websocket:
            await predictor_service.handle_message(websocket, message)
    except websockets.ConnectionClosed:
        LOGGER.info("Client disconnected")
    except Exception:
        LOGGER.exception("Unexpected WebSocket handler failure")


async def serve_async(host: str = "localhost", port: int = 8765, model_path: str | None = None) -> None:
    predictor = HeuristicMarketPredictor(model_path)
    service = PredictorWebSocketService(predictor)

    stop_event = asyncio.Event()

    def request_stop() -> None:
        LOGGER.info("Stopping predictor service")
        stop_event.set()

    loop = asyncio.get_running_loop()
    try:
        loop.add_signal_handler(signal.SIGINT, request_stop)
        loop.add_signal_handler(signal.SIGTERM, request_stop)
    except NotImplementedError:
        pass

    async with websockets.serve(
            lambda ws: websocket_handler(ws, service),
            host,
            port,
            ping_interval=20,
            ping_timeout=20,
            max_size=2 * 1024 * 1024,
    ):
        LOGGER.info("InvestPro Python predictor WebSocket listening on ws://%s:%s/ai", host, port)
        await stop_event.wait()


def serve(host: str = "localhost", port: int = 8765, model_path: str | None = None) -> None:
    asyncio.run(serve_async(host=host, port=port, model_path=model_path))


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the InvestPro Python WebSocket predictor.")
    parser.add_argument("--host", default="localhost", help="Host/IP to bind. Defaults to localhost.")
    parser.add_argument("--port", type=int, default=8765, help="Port to bind. Defaults to 8765.")
    parser.add_argument("--model-path", default=None, help="Optional JSON weight config for the heuristic predictor.")
    parser.add_argument("--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s"
    )
    serve(host=args.host, port=args.port, model_path=args.model_path)


if __name__ == "__main__":
    main()