package org.investpro.models.market;

public enum ProductVenue {
    COINBASE_ADVANCED,
    COINBASE_DERIVATIVES,
    COINBASE_INTERNATIONAL,

    OANDA,

    BINANCE_SPOT,
    BINANCE_US_SPOT,
    KRAKEN_SPOT,
    BITFINEX_SPOT,
    BITFINEX_US_SPOT,
    BITMEX_DERIVATIVES,
    KUCOIN_SPOT,
    KUCOIN_US_SPOT,
    BITSTAMP_SPOT,
    POLONIEX_SPOT,
    BITTREX_SPOT,
    IG,
    SCHWAB_EQUITIES,

    ALPACA_EQUITIES,
    ALPACA_CRYPTO,

    IBKR_SMART,
    IBKR_ARCA,
    IBKR_NASDAQ,
    IBKR_NYSE,
    IBKR_CME,
    IBKR_CBOE,
    IBKR_IDEALPRO,

    STELLAR_DEX,
    SOLANA_DEX,

    UNKNOWN
}
