package org.investpro.activity.reconciliation;

public enum MismatchType {
    MISSING_IN_LOCAL, MISSING_IN_BROKER, QUANTITY_MISMATCH, PRICE_MISMATCH, STATUS_MISMATCH,
    PNL_MISMATCH, FEE_MISMATCH, BALANCE_MISMATCH, DUPLICATE_EVENT, UNKNOWN
}
