package org.investpro.activity.reconciliation;

public enum MismatchType {
    LOCAL_ORDER_MISSING_ON_BROKER,
    BROKER_ORDER_MISSING_LOCALLY,
    LOCAL_POSITION_MISMATCH,
    BROKER_POSITION_MISSING_LOCALLY,
    LOCAL_BALANCE_MISMATCH,
    CLOSED_TRADE_MISSING,
    DUPLICATE_FILL_DETECTED,
    PENDING_CONFIRMATION_TIMEOUT,
    CURSOR_GAP_DETECTED,
    PROJECTION_FAILURE
}
