package org.investpro.decision;

import lombok.Data;
import org.investpro.models.trading.TradePair;
import org.investpro.strategy.signals.SignalDecision;
import org.investpro.utils.Side;
import org.jetbrains.annotations.Nullable;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Institutional-grade trade decision envelope.
 *
 * <p>Produced by {@link BotTradeDecisionEngine} after evaluating a market signal through
 * the full validation pipeline. This class serves as the backward-compatible API surface;
 * the new pipeline components ({@link TradeIntent}, {@link RiskEvaluation},
 * {@link ExecutionPlan}, etc.) are referenced by composition as fully {@code final} fields.</p>
 *
 * <h3>Immutability guarantee:</h3>
 * <p>All fields are {@code final}. There are no mutable setters or late-attachment methods.
 * The {@link BotTradeDecisionAssembler} is responsible for constructing fully-populated
 * instances when bridging from the new pipeline to legacy consumers.</p>
 *
 * <h3>Key architectural improvements:</h3>
 * <ul>
 *   <li>{@code confidence} is stored as a plain {@code double} — not {@link BigDecimal}.</li>
 *   <li>Decision IDs generated by {@link DecisionIdGenerator}: UUID for LIVE/PAPER,
 *       sequential longs for SIMULATION/LIGHTWEIGHT.</li>
 *   <li>{@link DecisionContext} replaces the untyped {@code Map<String,Object> metadata}.</li>
 *   <li>{@link DecisionStatus} tracks the full decision lifecycle for audit trails.</li>
 *   <li>Pipeline components are immutable final fields — no mutable late-attachment.</li>
 * </ul>
 *
 * <p>All existing accessor methods are preserved for backward compatibility with
 * {@link BotDecisionEngine}, {@link SignalToDecisionFilter}, and
 * {@link org.investpro.risk.RiskEngine}.</p>
 */
@Data
public final class BotTradeDecision {

    // ─── Inner enums ──────────────────────────────────────────────────────────

    public enum FinalAction {
        TRADE("Trade"),
        SKIP("Skip"),
        WAIT("Wait"),
        HOLD("Hold"),
        REDUCE_SIZE("Reduce size"),
        CLOSE("Close");

        public final String description;

        FinalAction(String description) {
            this.description = description;
        }
    }

    // ─── Core identity ────────────────────────────────────────────────────────

    private final String decisionId;
    private final DecisionStatus status;
    private final DecisionMode mode;

    // ─── Legacy fields (preserved for backward compatibility) ─────────────────

    private final DecisionAction action;
    private final boolean tradeAllowed;
    /** Confidence as a plain double — not BigDecimal. Stored as double to avoid GC overhead. */
    private final double confidenceValue;
    private final String explanation;
    private final SignalDecision signalDecision;
    private final List<String> blockers;
    private final List<String> warnings;
    private final List<String> reasons;
    private final Instant decidedAt;

    /** Typed context replaces the old Map<String,Object> metadata. */
    @Nullable
    private final DecisionContext decisionContext;

    private final TradePair tradePair;
    private final Side side;
    private final MarketRegime regime;
    private final AssetMarketType assetType;
    private final SetupSource setupSource;
    private final String selectedStrategyName;
    private final String indicatorSetupType;
    private final StrategyFitScore bestStrategyScore;
    private final IndicatorSetupScore indicatorSetupScore;
    private final TradeCostEstimate costEstimate;
    private final TradeExpectation expectation;
    private final HoldingPeriodEstimate holdingPeriodEstimate;
    private final FinalAction finalAction;
    private final String fullAnalysisSummary;

    // ─── New pipeline composition (fully final — no mutable setters) ──────────

    @Nullable private final TradeIntent tradeIntent;
    @Nullable private final RiskEvaluation riskEvaluation;
    @Nullable private final ExecutionPlan executionPlan;
    @Nullable private final DecisionReasoning reasoning;
    @Nullable private final PortfolioImpact portfolioImpact;
    @Nullable private final DecisionScoreBreakdown scoreBreakdown;

    // ─── Constructor 1: signal-layer decisions (BotDecisionEngine) ────────────

    /**
     * Creates a decision from a {@link SignalDecision} and market context.
     * Used by {@link BotDecisionEngine}.
     *
     * @param decisionId     nullable; generated by {@link DecisionIdGenerator} if blank
     * @param action         high-level action; defaults to HOLD if null
     * @param tradeAllowed   whether the decision permits execution
     * @param confidence     signal confidence (0.0–1.0); not BigDecimal
     * @param explanation    human-readable reason
     * @param signalDecision the originating aggregated signal
     * @param blockers       hard stop reasons
     * @param warnings       non-fatal caveats
     * @param decidedAt      timestamp; Instant.now() if null
     * @param context        typed decision context; replaces Map&lt;String,Object&gt; metadata
     */
    public BotTradeDecision(
            String decisionId,
            DecisionAction action,
            boolean tradeAllowed,
            double confidence,
            String explanation,
            SignalDecision signalDecision,
            List<String> blockers,
            List<String> warnings,
            Instant decidedAt,
            @Nullable DecisionContext context) {

        this.mode = DecisionMode.LIVE;
        this.decisionId = safeId(decisionId, this.mode);
        this.status = tradeAllowed ? DecisionStatus.EXECUTION_PENDING : DecisionStatus.RISK_REJECTED;
        this.action = action == null ? DecisionAction.HOLD : action;
        this.tradeAllowed = tradeAllowed;
        this.confidenceValue = clampConfidence(confidence);
        this.explanation = safe(explanation);
        this.signalDecision = signalDecision;
        this.blockers = copy(blockers);
        this.warnings = copy(warnings);
        this.reasons = this.explanation.isBlank() ? List.of() : List.of(this.explanation);
        this.decidedAt = decidedAt == null ? Instant.now() : decidedAt;
        this.decisionContext = context;
        this.tradePair = null;
        this.side = null;
        this.regime = null;
        this.assetType = null;
        this.setupSource = null;
        this.selectedStrategyName = "";
        this.indicatorSetupType = "";
        this.bestStrategyScore = null;
        this.indicatorSetupScore = null;
        this.costEstimate = null;
        this.expectation = null;
        this.holdingPeriodEstimate = null;
        this.finalAction = tradeAllowed ? FinalAction.TRADE : FinalAction.SKIP;
        this.fullAnalysisSummary = this.explanation;
        this.tradeIntent = null;
        this.riskEvaluation = null;
        this.executionPlan = null;
        this.reasoning = null;
        this.portfolioImpact = null;
        this.scoreBreakdown = null;
    }

    /**
     * Backward-compatible constructor accepting {@code BigDecimal confidence}.
     * Converts to double internally — {@link BigDecimal} is not appropriate for scoring metrics.
     *
     * @deprecated Use the {@code double} overload. This overload exists only for legacy callers.
     */
    @Deprecated
    public BotTradeDecision(
            String decisionId,
            DecisionAction action,
            boolean tradeAllowed,
            BigDecimal confidence,
            String explanation,
            SignalDecision signalDecision,
            List<String> blockers,
            List<String> warnings,
            Instant decidedAt,
            Map<String, Object> metadata) {

        this(decisionId, action, tradeAllowed,
                confidence == null ? 0.0 : confidence.doubleValue(),
                explanation, signalDecision, blockers, warnings, decidedAt,
                DecisionContext.empty());
    }

    // ─── Constructor 2: full decision engine output (BotTradeDecisionEngine) ──

    /**
     * Creates a complete institutional decision from the evaluation engine output.
     * Used by {@link BotTradeDecisionEngine}.
     *
     * @param mode execution mode controlling allocation and ID strategy
     */
    public BotTradeDecision(
            TradePair tradePair,
            Side side,
            MarketRegime regime,
            AssetMarketType assetType,
            SetupSource setupSource,
            String selectedStrategyName,
            String indicatorSetupType,
            StrategyFitScore bestStrategyScore,
            IndicatorSetupScore indicatorSetupScore,
            TradeCostEstimate costEstimate,
            TradeExpectation expectation,
            HoldingPeriodEstimate holdingPeriodEstimate,
            FinalAction finalAction,
            List<String> reasons,
            List<String> warnings,
            List<String> blockers,
            String fullAnalysisSummary,
            Instant decidedAt,
            DecisionMode mode) {

        this.mode = mode != null ? mode : DecisionMode.LIVE;
        this.decisionId = DecisionIdGenerator.generate(this.mode);
        this.finalAction = finalAction == null ? FinalAction.HOLD : finalAction;
        this.action = switch (this.finalAction) {
            case TRADE -> DecisionAction.TRADE;
            case WAIT  -> DecisionAction.WAIT;
            case REDUCE_SIZE -> DecisionAction.REDUCE_SIZE;
            case CLOSE -> DecisionAction.CLOSE;
            case HOLD  -> DecisionAction.HOLD;
            case SKIP  -> DecisionAction.SKIP;
        };
        this.tradeAllowed = this.finalAction == FinalAction.TRADE;
        this.status = this.tradeAllowed
                ? DecisionStatus.EXECUTION_PENDING
                : (blockers != null && !blockers.isEmpty()
                        ? DecisionStatus.RISK_REJECTED
                        : DecisionStatus.VALIDATED);
        this.confidenceValue = clampConfidence(
                indicatorSetupScore == null ? 0.0 : indicatorSetupScore.finalFitnessScore());
        this.explanation = safe(fullAnalysisSummary);
        this.signalDecision = null;
        this.blockers = copy(blockers);
        this.warnings = copy(warnings);
        this.reasons = copy(reasons);
        this.decidedAt = decidedAt == null ? Instant.now() : decidedAt;
        this.decisionContext = null;
        this.tradePair = tradePair;
        this.side = side;
        this.regime = regime;
        this.assetType = assetType;
        this.setupSource = setupSource;
        this.selectedStrategyName = safe(selectedStrategyName);
        this.indicatorSetupType = safe(indicatorSetupType);
        this.bestStrategyScore = bestStrategyScore;
        this.indicatorSetupScore = indicatorSetupScore;
        this.costEstimate = costEstimate;
        this.expectation = expectation;
        this.holdingPeriodEstimate = holdingPeriodEstimate;
        this.fullAnalysisSummary = safe(fullAnalysisSummary);
        this.tradeIntent = null;
        this.riskEvaluation = null;
        this.executionPlan = null;
        this.reasoning = null;
        this.portfolioImpact = null;
        this.scoreBreakdown = null;
    }

    /**
     * Backward-compatible factory preserving the original 18-argument signature.
     * Defaults to {@link DecisionMode#LIVE}.
     */
    public BotTradeDecision(
            TradePair tradePair,
            Side side,
            MarketRegime regime,
            AssetMarketType assetType,
            SetupSource setupSource,
            String selectedStrategyName,
            String indicatorSetupType,
            StrategyFitScore bestStrategyScore,
            IndicatorSetupScore indicatorSetupScore,
            TradeCostEstimate costEstimate,
            TradeExpectation expectation,
            HoldingPeriodEstimate holdingPeriodEstimate,
            FinalAction finalAction,
            List<String> reasons,
            List<String> warnings,
            List<String> blockers,
            String fullAnalysisSummary,
            Instant decidedAt) {

        this(tradePair, side, regime, assetType, setupSource,
                selectedStrategyName, indicatorSetupType,
                bestStrategyScore, indicatorSetupScore, costEstimate,
                expectation, holdingPeriodEstimate, finalAction,
                reasons, warnings, blockers, fullAnalysisSummary, decidedAt,
                DecisionMode.LIVE);
    }

    // ─── Private pipeline constructor (used by BotTradeDecisionAssembler) ─────

    /**
     * Private constructor that accepts all pipeline components as fully-initialized
     * final fields. This eliminates the mutable late-attachment anti-pattern.
     *
     * <p>Only {@link BotTradeDecisionAssembler} should call this constructor.</p>
     */
    BotTradeDecision(
            String decisionId,
            DecisionStatus status,
            DecisionMode mode,
            DecisionAction action,
            boolean tradeAllowed,
            double confidenceValue,
            String explanation,
            SignalDecision signalDecision,
            List<String> blockers,
            List<String> warnings,
            List<String> reasons,
            Instant decidedAt,
            @Nullable DecisionContext decisionContext,
            TradePair tradePair,
            Side side,
            MarketRegime regime,
            AssetMarketType assetType,
            SetupSource setupSource,
            String selectedStrategyName,
            String indicatorSetupType,
            StrategyFitScore bestStrategyScore,
            IndicatorSetupScore indicatorSetupScore,
            TradeCostEstimate costEstimate,
            TradeExpectation expectation,
            HoldingPeriodEstimate holdingPeriodEstimate,
            FinalAction finalAction,
            String fullAnalysisSummary,
            @Nullable TradeIntent tradeIntent,
            @Nullable RiskEvaluation riskEvaluation,
            @Nullable ExecutionPlan executionPlan,
            @Nullable DecisionReasoning reasoning,
            @Nullable PortfolioImpact portfolioImpact,
            @Nullable DecisionScoreBreakdown scoreBreakdown) {

        this.decisionId = decisionId;
        this.status = status;
        this.mode = mode;
        this.action = action;
        this.tradeAllowed = tradeAllowed;
        this.confidenceValue = confidenceValue;
        this.explanation = explanation;
        this.signalDecision = signalDecision;
        this.blockers = blockers;
        this.warnings = warnings;
        this.reasons = reasons;
        this.decidedAt = decidedAt;
        this.decisionContext = decisionContext;
        this.tradePair = tradePair;
        this.side = side;
        this.regime = regime;
        this.assetType = assetType;
        this.setupSource = setupSource;
        this.selectedStrategyName = selectedStrategyName;
        this.indicatorSetupType = indicatorSetupType;
        this.bestStrategyScore = bestStrategyScore;
        this.indicatorSetupScore = indicatorSetupScore;
        this.costEstimate = costEstimate;
        this.expectation = expectation;
        this.holdingPeriodEstimate = holdingPeriodEstimate;
        this.finalAction = finalAction;
        this.fullAnalysisSummary = fullAnalysisSummary;
        this.tradeIntent = tradeIntent;
        this.riskEvaluation = riskEvaluation;
        this.executionPlan = executionPlan;
        this.reasoning = reasoning;
        this.portfolioImpact = portfolioImpact;
        this.scoreBreakdown = scoreBreakdown;
    }

    // ─── Pipeline component accessors ─────────────────────────────────────────

    /** Returns the {@link TradeIntent} from the new pipeline, if available. */
    @Nullable public TradeIntent tradeIntent()           { return tradeIntent; }

    /** Returns the {@link RiskEvaluation} from the new pipeline, if available. */
    @Nullable public RiskEvaluation riskEvaluation()    { return riskEvaluation; }

    /** Returns the {@link ExecutionPlan} from the new pipeline, if available. */
    @Nullable public ExecutionPlan executionPlan()       { return executionPlan; }

    /** Returns the {@link DecisionReasoning} from the new pipeline, if available. */
    @Nullable public DecisionReasoning reasoning()       { return reasoning; }

    /** Returns the {@link PortfolioImpact} from the new pipeline, if available. */
    @Nullable public PortfolioImpact portfolioImpact()  { return portfolioImpact; }

    /** Returns the {@link DecisionScoreBreakdown} from the new pipeline, if available. */
    @Nullable public DecisionScoreBreakdown scoreBreakdown() { return scoreBreakdown; }

    // ─── Backward-compatible accessors ────────────────────────────────────────

    public String decisionId()                { return decisionId; }
    public DecisionStatus status()            { return status; }
    public DecisionMode mode()                { return mode; }
    public DecisionAction action()            { return action; }
    public boolean tradeAllowed()             { return tradeAllowed; }
    public String explanation()               { return explanation; }
    public SignalDecision signalDecision()    { return signalDecision; }
    public List<String> blockers()            { return blockers; }
    public List<String> warnings()            { return warnings; }
    public List<String> reasons()             { return reasons; }
    public Instant decidedAt()               { return decidedAt; }
    public TradeExpectation expectation()     { return expectation; }
    public String fullAnalysisSummary()       { return fullAnalysisSummary; }

    /**
     * Returns the decision confidence as a double (0.0–1.0).
     * This is the preferred accessor — confidence is a scoring metric, not money.
     */
    public double confidenceValue()           { return confidenceValue; }

    /**
     * Returns confidence as {@link BigDecimal} for legacy consumers.
     * New code should use {@link #confidenceValue()} instead.
     *
     * @deprecated Use {@link #confidenceValue()} to avoid unnecessary BigDecimal allocation.
     */
    @Deprecated
    public BigDecimal confidence()            { return BigDecimal.valueOf(confidenceValue); }

    /**
     * Returns the typed {@link DecisionContext}.
     */
    @Nullable public DecisionContext decisionContext() { return decisionContext; }

    /**
     * Returns the legacy untyped metadata map.
     * Always returns an empty map — metadata is now in {@link #decisionContext()}.
     *
     * @deprecated Use {@link #decisionContext()} for typed field access.
     */
    @Deprecated
    public Map<String, Object> metadata()     { return Map.of(); }

    public boolean hasBlockingIssues() {
        return !blockers.isEmpty();
    }

    public boolean willSkip() {
        return finalAction == FinalAction.SKIP || action == DecisionAction.SKIP || !tradeAllowed;
    }

    public String getDecisionSummary() {
        return finalAction.description + ": "
                + (fullAnalysisSummary.isBlank() ? explanation : fullAnalysisSummary);
    }

    public String getSetupSourceDescription() {
        return setupSource == null ? "Unknown" : setupSource.name();
    }

    // ─── Utility methods ──────────────────────────────────────────────────────

    private static List<String> copy(List<String> values) {
        return values == null ? List.of() : List.copyOf(values);
    }

    private static String safe(String value) {
        return value == null ? "" : value.trim();
    }

    private static String safeId(String value, DecisionMode mode) {
        if (value != null && !value.isBlank()) return value.trim();
        return DecisionIdGenerator.generate(mode);
    }

    private static double clampConfidence(double v) {
        return Math.max(0.0, Math.min(1.0, v));
    }

    // ─── Pipeline bridge factory ──────────────────────────────────────────────

    /**
     * Creates a {@link BotTradeDecision} from a fully evaluated {@link ExecutionDecision}.
     * Delegates to {@link BotTradeDecisionAssembler} — no mutable setters are used.
     */
    public static BotTradeDecision fromPipeline(
            ExecutionDecision execDecision,
            @Nullable TradeCostEstimate costEstimate,
            @Nullable TradeExpectation expectation) {
        return org.investpro.decision.BotTradeDecisionAssembler.assemble(execDecision, costEstimate, expectation);
    }
}


/**
 * Institutional-grade trade decision envelope.
 *
 * <p>Produced by {@link BotTradeDecisionEngine} after evaluating a market signal through
 * the full validation pipeline. This class serves as the backward-compatible API surface;
 * the new pipeline components ({@link TradeIntent}, {@link RiskEvaluation},
 * {@link ExecutionPlan}, etc.) are referenced by composition.</p>
 *
 * <h3>Key architectural improvements over the legacy design:</h3>
 * <ul>
 *   <li>{@code confidence} is stored as a plain {@code double} — not {@link BigDecimal}.
 *       Confidence is a scoring metric, not money. {@link BigDecimal} was wasteful overhead.</li>
 *   <li>Decision IDs are generated by {@link DecisionIdGenerator}: UUID for LIVE/PAPER modes,
 *       cheap sequential longs for SIMULATION/LIGHTWEIGHT modes.</li>
 *   <li>{@link DecisionContext} replaces the untyped {@code Map<String,Object> metadata}.</li>
 *   <li>{@link DecisionStatus} tracks the full decision lifecycle for audit trails.</li>
 *   <li>The new pipeline objects ({@link TradeIntent}, {@link RiskEvaluation},
 *       {@link ExecutionPlan}, {@link DecisionReasoning}, {@link PortfolioImpact},
 *       {@link DecisionScoreBreakdown}) are composed in rather than monolithically inlined.</li>
 * </ul>
 *
 * <p>All existing accessor methods are preserved for backward compatibility with
 * {@link BotDecisionEngine}, {@link SignalToDecisionFilter}, and
 * {@link org.investpro.risk.RiskEngine}.</p>
 */
@SuppressWarnings("all") // LEGACY TOMBSTONE — will be removed in a future sprint
class _OldBotTradeDecisionBody_TOBEDELETED {

    // ─── Inner enums ──────────────────────────────────────────────────────────

    public enum FinalAction {
        TRADE("Trade"),
        SKIP("Skip"),
        WAIT("Wait"),
        HOLD("Hold"),
        REDUCE_SIZE("Reduce size"),
        CLOSE("Close");

        public final String description;

        FinalAction(String description) {
            this.description = description;
        }
    }

    // ─── Core identity ────────────────────────────────────────────────────────

    private final String decisionId;
    private final DecisionStatus status;
    private final DecisionMode mode;

    // ─── Legacy fields (preserved for backward compatibility) ─────────────────

    private final DecisionAction action;
    private final boolean tradeAllowed;
    /** Confidence as a plain double — not BigDecimal. Stored as double to avoid GC overhead. */
    private final double confidenceValue;
    private final String explanation;
    private final SignalDecision signalDecision;
    private final List<String> blockers;
    private final List<String> warnings;
    private final List<String> reasons;
    private final Instant decidedAt;

    /** Typed context replaces the old Map<String,Object> metadata. */
    @Nullable
    private final DecisionContext decisionContext;

    private final TradePair tradePair;
    private final Side side;
    private final MarketRegime regime;
    private final AssetMarketType assetType;
    private final SetupSource setupSource;
    private final String selectedStrategyName;
    private final String indicatorSetupType;
    private final StrategyFitScore bestStrategyScore;
    private final IndicatorSetupScore indicatorSetupScore;
    private final TradeCostEstimate costEstimate;
    private final TradeExpectation expectation;
    private final HoldingPeriodEstimate holdingPeriodEstimate;
    private final FinalAction finalAction;
    private final String fullAnalysisSummary;

    // ─── New pipeline composition ─────────────────────────────────────────────

    @Nullable private final TradeIntent tradeIntent;
    @Nullable private final RiskEvaluation riskEvaluation;
    @Nullable private final ExecutionPlan executionPlan;
    @Nullable private final DecisionReasoning reasoning;
    @Nullable private final PortfolioImpact portfolioImpact;
    @Nullable private final DecisionScoreBreakdown scoreBreakdown;

    // ─── Constructor 1: signal-layer decisions (BotDecisionEngine) ────────────

    /**
     * Creates a decision from a {@link SignalDecision} and market context.
     * Used by {@link BotDecisionEngine}.
     *
     * @param decisionId   nullable; generated by {@link DecisionIdGenerator} if blank
     * @param action       high-level action; defaults to HOLD if null
     * @param tradeAllowed whether the decision permits execution
     * @param confidence   signal confidence (0.0–1.0); not BigDecimal
     * @param explanation  human-readable reason
     * @param signalDecision the originating aggregated signal
     * @param blockers     hard stop reasons
     * @param warnings     non-fatal caveats
     * @param decidedAt    timestamp; Instant.now() if null
     * @param context      typed decision context; replaces Map&lt;String,Object&gt; metadata
     */
    public _OldBotTradeDecisionBody_TOBEDELETED(
            String decisionId,
            DecisionAction action,
            boolean tradeAllowed,
            double confidence,
            String explanation,
            SignalDecision signalDecision,
            List<String> blockers,
            List<String> warnings,
            Instant decidedAt,
            @Nullable DecisionContext context) {

        this.mode = DecisionMode.LIVE;
        this.decisionId = safeId(decisionId, this.mode);
        this.status = tradeAllowed ? DecisionStatus.EXECUTION_PENDING : DecisionStatus.RISK_REJECTED;
        this.action = action == null ? DecisionAction.HOLD : action;
        this.tradeAllowed = tradeAllowed;
        this.confidenceValue = clampConfidence(confidence);
        this.explanation = safe(explanation);
        this.signalDecision = signalDecision;
        this.blockers = copy(blockers);
        this.warnings = copy(warnings);
        this.reasons = this.explanation.isBlank() ? List.of() : List.of(this.explanation);
        this.decidedAt = decidedAt == null ? Instant.now() : decidedAt;
        this.decisionContext = context;
        this.tradePair = null;
        this.side = null;
        this.regime = null;
        this.assetType = null;
        this.setupSource = null;
        this.selectedStrategyName = "";
        this.indicatorSetupType = "";
        this.bestStrategyScore = null;
        this.indicatorSetupScore = null;
        this.costEstimate = null;
        this.expectation = null;
        this.holdingPeriodEstimate = null;
        this.finalAction = tradeAllowed ? FinalAction.TRADE : FinalAction.SKIP;
        this.fullAnalysisSummary = this.explanation;
        this.tradeIntent = null;
        this.riskEvaluation = null;
        this.executionPlan = null;
        this.reasoning = null;
        this.portfolioImpact = null;
        this.scoreBreakdown = null;
    }

    /**
     * Backward-compatible constructor accepting {@code BigDecimal confidence}.
     * Converts to double internally — {@link BigDecimal} is not appropriate for scoring metrics.
     *
     * @deprecated Use the {@code double} overload. This overload exists only for legacy callers.
     */
    @Deprecated
    public _OldBotTradeDecisionBody_TOBEDELETED(
            String decisionId,
            DecisionAction action,
            boolean tradeAllowed,
            BigDecimal confidence,
            String explanation,
            SignalDecision signalDecision,
            List<String> blockers,
            List<String> warnings,
            Instant decidedAt,
            Map<String, Object> metadata) {

        this(decisionId, action, tradeAllowed,
                confidence == null ? 0.0 : confidence.doubleValue(),
                explanation, signalDecision, blockers, warnings, decidedAt,
                DecisionContext.empty());
    }

    // ─── Constructor 2: full decision engine output (BotTradeDecisionEngine) ──

    /**
     * Creates a complete institutional decision from the evaluation engine output.
     * Used by {@link BotTradeDecisionEngine}.
     *
     * @param mode execution mode controlling allocation and ID strategy
     */
    public _OldBotTradeDecisionBody_TOBEDELETED(
            TradePair tradePair,
            Side side,
            MarketRegime regime,
            AssetMarketType assetType,
            SetupSource setupSource,
            String selectedStrategyName,
            String indicatorSetupType,
            StrategyFitScore bestStrategyScore,
            IndicatorSetupScore indicatorSetupScore,
            TradeCostEstimate costEstimate,
            TradeExpectation expectation,
            HoldingPeriodEstimate holdingPeriodEstimate,
            FinalAction finalAction,
            List<String> reasons,
            List<String> warnings,
            List<String> blockers,
            String fullAnalysisSummary,
            Instant decidedAt,
            DecisionMode mode) {

        this.mode = mode != null ? mode : DecisionMode.LIVE;
        this.decisionId = DecisionIdGenerator.generate(this.mode);
        this.finalAction = finalAction == null ? FinalAction.HOLD : finalAction;
        this.action = switch (this.finalAction) {
            case TRADE -> DecisionAction.TRADE;
            case WAIT  -> DecisionAction.WAIT;
            case REDUCE_SIZE -> DecisionAction.REDUCE_SIZE;
            case CLOSE -> DecisionAction.CLOSE;
            case HOLD  -> DecisionAction.HOLD;
            case SKIP  -> DecisionAction.SKIP;
        };
        this.tradeAllowed = this.finalAction == FinalAction.TRADE;
        this.status = this.tradeAllowed
                ? DecisionStatus.EXECUTION_PENDING
                : (blockers != null && !blockers.isEmpty()
                        ? DecisionStatus.RISK_REJECTED
                        : DecisionStatus.VALIDATED);
        this.confidenceValue = clampConfidence(
                indicatorSetupScore == null ? 0.0 : indicatorSetupScore.finalFitnessScore());
        this.explanation = safe(fullAnalysisSummary);
        this.signalDecision = null;
        this.blockers = copy(blockers);
        this.warnings = copy(warnings);
        this.reasons = copy(reasons);
        this.decidedAt = decidedAt == null ? Instant.now() : decidedAt;
        this.decisionContext = null;
        this.tradePair = tradePair;
        this.side = side;
        this.regime = regime;
        this.assetType = assetType;
        this.setupSource = setupSource;
        this.selectedStrategyName = safe(selectedStrategyName);
        this.indicatorSetupType = safe(indicatorSetupType);
        this.bestStrategyScore = bestStrategyScore;
        this.indicatorSetupScore = indicatorSetupScore;
        this.costEstimate = costEstimate;
        this.expectation = expectation;
        this.holdingPeriodEstimate = holdingPeriodEstimate;
        this.fullAnalysisSummary = safe(fullAnalysisSummary);
        this.tradeIntent = null;
        this.riskEvaluation = null;
        this.executionPlan = null;
        this.reasoning = null;
        this.portfolioImpact = null;
        this.scoreBreakdown = null;
    }

    /**
     * Backward-compatible factory preserving the original 18-argument signature.
     * Defaults to {@link DecisionMode#LIVE}.
     */
    public _OldBotTradeDecisionBody_TOBEDELETED(
            TradePair tradePair,
            Side side,
            MarketRegime regime,
            AssetMarketType assetType,
            SetupSource setupSource,
            String selectedStrategyName,
            String indicatorSetupType,
            StrategyFitScore bestStrategyScore,
            IndicatorSetupScore indicatorSetupScore,
            TradeCostEstimate costEstimate,
            TradeExpectation expectation,
            HoldingPeriodEstimate holdingPeriodEstimate,
            FinalAction finalAction,
            List<String> reasons,
            List<String> warnings,
            List<String> blockers,
            String fullAnalysisSummary,
            Instant decidedAt) {

        this(tradePair, side, regime, assetType, setupSource,
                selectedStrategyName, indicatorSetupType,
                bestStrategyScore, indicatorSetupScore, costEstimate,
                expectation, holdingPeriodEstimate, finalAction,
                reasons, warnings, blockers, fullAnalysisSummary, decidedAt,
                DecisionMode.LIVE);
    }

    // Pipeline bridge: removed — use BotTradeDecisionAssembler.assemble()

    // ─── Backward-compatible accessors ────────────────────────────────────────

    public String decisionId()                { return decisionId; }
    public DecisionStatus status()            { return status; }
    public DecisionMode mode()                { return mode; }
    public DecisionAction action()            { return action; }
    public boolean tradeAllowed()             { return tradeAllowed; }
    public String explanation()               { return explanation; }
    public SignalDecision signalDecision()    { return signalDecision; }
    public List<String> blockers()            { return blockers; }
    public List<String> warnings()            { return warnings; }
    public List<String> reasons()             { return reasons; }
    public Instant decidedAt()               { return decidedAt; }
    public TradeExpectation expectation()     { return expectation; }
    public String fullAnalysisSummary()       { return fullAnalysisSummary; }

    /**
     * Returns the decision confidence as a double (0.0–1.0).
     * This is the preferred accessor — confidence is a scoring metric, not money.
     */
    public double confidenceValue()           { return confidenceValue; }

    /**
     * Returns confidence as {@link BigDecimal} for legacy consumers.
     * New code should use {@link #confidenceValue()} instead.
     *
     * @deprecated Use {@link #confidenceValue()} to avoid unnecessary BigDecimal allocation.
     */
    @Deprecated
    public BigDecimal confidence()            { return BigDecimal.valueOf(confidenceValue); }

    /**
     * Returns the typed {@link DecisionContext}. Null if this decision was built
     * from the legacy map-based metadata API.
     */
    @Nullable public DecisionContext decisionContext() { return decisionContext; }

    /**
     * Returns the legacy untyped metadata map.
     * Always returns an empty map — metadata is now in {@link #decisionContext()}.
     *
     * @deprecated Use {@link #decisionContext()} for typed field access.
     */
    @Deprecated
    public Map<String, Object> metadata()     { return Map.of(); }

    public boolean hasBlockingIssues() {
        return !blockers.isEmpty();
    }

    public boolean willSkip() {
        return finalAction == FinalAction.SKIP || action == DecisionAction.SKIP || !tradeAllowed;
    }

    public String getDecisionSummary() {
        return finalAction.description + ": "
                + (fullAnalysisSummary.isBlank() ? explanation : fullAnalysisSummary);
    }

    public String getSetupSourceDescription() {
        return setupSource == null ? "Unknown" : setupSource.name();
    }

    // ─── Utility methods ──────────────────────────────────────────────────────

    private static List<String> copy(List<String> values) {
        return values == null ? List.of() : List.copyOf(values);
    }

    private static String safe(String value) {
        return value == null ? "" : value.trim();
    }

    private static String safeId(String value, DecisionMode mode) {
        if (value != null && !value.isBlank()) return value.trim();
        return DecisionIdGenerator.generate(mode);
    }

    private static double clampConfidence(double v) {
        return Math.max(0.0, Math.min(1.0, v));
    }
}
